### ISSUE TITLE
Increasing the FPS

### ISSUE THREAD

**Issue by vvkv** [hollance/YOLO-CoreML-MPSNNGraph#16]
Thank you so much for your very inspiring work here. I am curious as to what parameter controls the fps at which the app runs at. I understand a higher fps requires more processing power but doesn't an iPhone have the processing power we need to crank up the fps even further? 
This isn't so much an issue as it is a concept question. Thanks

**Comment by hollance** [comment]
The camera runs at 30 fps so that is the max (although you can also run at 60 fps, I think). However, in this example app the effective fps is limited by how fast/slow the neural net runs. And in this app it runs pretty much full speed, so it's not going to get any faster than what you see here. The only way to make it faster is to change the architecture of the neural net so that it uses less memory / compute, or to make the input images smaller.
